services:
  ms_auth:
    build: .
    image: benjamorenoo/ms_auth:latest
    container_name: ms_auth
    ports:
      - "3001:3001"
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: equiporocketDb
      DB_USER: postgres
      DB_PASSWORD: example
      PORT: 3001
      JWT_SECRET: dev_jwt_secret
    networks:
      - equiporocket-net

networks:
  equiporocket-net:
    external: true
