services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - equiporocket-net
    restart: unless-stopped

networks:
  equiporocket-net:
    external: true