services:
  api_gateway:
    build:
      context: .
      dockerfile: Dockerfile
    image: benjamorenoo/ms_gateway:latest
    container_name: api_gateway
    restart: unless-stopped
    ports:
      - "9000:8000"
    environment:
      - PORT=8000
      - MS_AUTH_URL=http://ms_auth:3001
      - MS_USUARIOS_URL=http://ms_usuarios:3003
      - MS_POKEMON_URL=http://ms_pokemon:3002
      - MS_CARGA_API_URL=http://ms_carga_api:8000
      - MS_MONTECARLO_URL=http://ms_montecarlo:8010
      - MS_ASISTENCIA_URL=http://ms_asistencia:8005
    networks:
      - equiporocket-net
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/health"]
      interval: 30s
      timeout: 3s
      retries: 3

networks:
  equiporocket-net:
    external: true

