// src/utils/regions.js

export const REGIONS = [
  { id: 1, name: 'Latinoamérica'          },
  { id: 2, name: 'Norteamérica'           },
  { id: 3, name: 'Europa'                 },
  { id: 4, name: 'Asia-Pacífico'          },
  { id: 5, name: 'Medio Oriente y África' },
  { id: 6, name: 'Oceanía'               },
];

export const COUNTRIES_BY_REGION = {
  1: [
    { id: 1,  name: 'Argentina'           },
    { id: 2,  name: 'Bolivia'             },
    { id: 3,  name: 'Brasil'              },
    { id: 4,  name: 'Chile'               },
    { id: 5,  name: 'Colombia'            },
    { id: 6,  name: 'Costa Rica'          },
    { id: 7,  name: 'Cuba'                },
    { id: 8,  name: 'Ecuador'             },
    { id: 9,  name: 'El Salvador'         },
    { id: 10, name: 'Guatemala'           },
    { id: 11, name: 'Honduras'            },
    { id: 12, name: 'México'              },
    { id: 13, name: 'Nicaragua'           },
    { id: 14, name: 'Panamá'             },
    { id: 15, name: 'Paraguay'            },
    { id: 16, name: 'Perú'               },
    { id: 17, name: 'Puerto Rico'         },
    { id: 18, name: 'República Dominicana'},
    { id: 19, name: 'Uruguay'             },
    { id: 20, name: 'Venezuela'           },
  ],
  2: [
    { id: 21, name: 'Canadá'         },
    { id: 22, name: 'Estados Unidos' },
  ],
  3: [
    { id: 23, name: 'Alemania'        },
    { id: 24, name: 'Austria'         },
    { id: 25, name: 'Bélgica'        },
    { id: 26, name: 'Bulgaria'        },
    { id: 27, name: 'Chipre'          },
    { id: 28, name: 'Croacia'         },
    { id: 29, name: 'Dinamarca'       },
    { id: 30, name: 'Eslovaquia'      },
    { id: 31, name: 'Eslovenia'       },
    { id: 32, name: 'España'          },
    { id: 33, name: 'Estonia'         },
    { id: 34, name: 'Finlandia'       },
    { id: 35, name: 'Francia'         },
    { id: 36, name: 'Grecia'          },
    { id: 37, name: 'Hungría'        },
    { id: 38, name: 'Irlanda'         },
    { id: 39, name: 'Islandia'        },
    { id: 40, name: 'Italia'          },
    { id: 41, name: 'Letonia'         },
    { id: 42, name: 'Lituania'        },
    { id: 43, name: 'Luxemburgo'      },
    { id: 44, name: 'Malta'           },
    { id: 45, name: 'Noruega'         },
    { id: 46, name: 'Países Bajos'   },
    { id: 47, name: 'Polonia'         },
    { id: 48, name: 'Portugal'        },
    { id: 49, name: 'Reino Unido'     },
    { id: 50, name: 'República Checa' },
    { id: 51, name: 'Rumania'         },
    { id: 52, name: 'Suecia'          },
    { id: 53, name: 'Suiza'           },
    { id: 54, name: 'Turquía'        },
  ],
  4: [
    { id: 55, name: 'China'         },
    { id: 56, name: 'Corea del Sur' },
    { id: 57, name: 'Filipinas'     },
    { id: 58, name: 'Hong Kong'     },
    { id: 59, name: 'India'         },
    { id: 60, name: 'Indonesia'     },
    { id: 61, name: 'Japón'        },
    { id: 62, name: 'Malasia'       },
    { id: 63, name: 'Singapur'      },
    { id: 64, name: 'Taiwán'       },
    { id: 65, name: 'Tailandia'     },
    { id: 66, name: 'Vietnam'       },
  ],
  5: [
    { id: 67, name: 'Arabia Saudita'         },
    { id: 68, name: 'Emiratos Árabes Unidos'},
    { id: 69, name: 'Israel'                 },
    { id: 70, name: 'Jordania'               },
    { id: 71, name: 'Kuwait'                 },
    { id: 72, name: 'Marruecos'              },
    { id: 73, name: 'Qatar'                  },
    { id: 74, name: 'Sudáfrica'             },
  ],
  6: [
    { id: 75, name: 'Australia'      },
    { id: 76, name: 'Nueva Zelanda'  },
  ],
};

export const MONTHS = [
  { v: '01', label: 'Enero'      },
  { v: '02', label: 'Febrero'    },
  { v: '03', label: 'Marzo'      },
  { v: '04', label: 'Abril'      },
  { v: '05', label: 'Mayo'       },
  { v: '06', label: 'Junio'      },
  { v: '07', label: 'Julio'      },
  { v: '08', label: 'Agosto'     },
  { v: '09', label: 'Septiembre' },
  { v: '10', label: 'Octubre'    },
  { v: '11', label: 'Noviembre'  },
  { v: '12', label: 'Diciembre'  },
];